language: node_js
node_js:
- 12
services:
- mysql
before_install:
- openssl aes-256-cbc -K $encrypted_ad8ca1f2b447_key -iv $encrypted_ad8ca1f2b447_iv
  -in deploy.enc -out deploy -d
- mysql -e 'CREATE DATABASE ecorewards;'
install: npm install
before_script:
- npm run bdd-setup
- npm start &
scripts:
- npm run report-coverage
- npm run bdd
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy
- echo -e "Host 3.8.141.48\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy
- test $TRAVIS_BRANCH = "master" && ssh -i ./deploy ubuntu@3.8.141.48 pwd
- test $TRAVIS_BRANCH = "master" && npm install pm2 -g
- test $TRAVIS_BRANCH = "master" && pm2 deploy ecosystem.config.js production update
