language: node_js
node_js:
- 12
services:
- mysql
before_install:
- openssl aes-256-cbc -K $encrypted_ad8ca1f2b447_key -iv $encrypted_ad8ca1f2b447_iv
  -in deploy.enc -out ./deploy -d
- mysql -e 'CREATE DATABASE ecorewards;'
install: npm install
before_script:
- npm run bdd-setup
- npm start &
scripts:
- npm run report-coverage
- npm run bdd
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy
- ssh -i ./deploy ubuntu@35.178.27.220 pwd
