language: node_js
node_js:
  - 12
addons:
  mariadb: '10.0'
before_install:
  - mysql -e 'CREATE DATABASE ecorewards;'
install: npm install
before_script:
  - npm start &
scripts:
  - npm test
  - npm run report-coverage
  - npm run migrate
  - npm run add-test-user
  - npm run bdd
