swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Eco Rewards Hub API"
  contact:
    email: "linusnorton@gmail.com"
schemes:
  - "http"
  - "https"
paths:
  /health:
    get:
      summary: "Check the status of the service"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Health"

  /login:
    post:
      summary: "Authenticate an admin user"
      description: "This endpoint allows users generate a token so they can login to the admin user interface"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Username and password to authenticate"
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        401:
          description: "Unauthorized"
          schema:
            type: "object"
            properties:
              data:
                type: "object"
                properties:
                  error:
                    type: "string"
              links:
                type: "object"
        201:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "object"
                properties:
                  token:
                    type: "string"
              links:
                type: "object"

  /schemes:
    get:
      summary: "Return all the schemes"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Scheme"
              links:
                type: "object"
      security:
        - basicAuth: []

  /scheme/{schemeId}:
    get:
      summary: "Return a scheme"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "schemeId"
          in: "path"
          description: "ID of scheme to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        401:
          description: "Unauthorized"
          schema:
            type: "object"
            properties:
              data:
                type: "object"
                properties:
                  error:
                    type: "string"
              links:
                type: "object"
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Scheme"
              links:
                type: "object"
      security:
        - basicAuth: []

  /organisations:
    get:
      summary: "Return all the organisations"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        401:
          description: "Unauthorized"
          schema:
            type: "object"
            properties:
              data:
                type: "object"
                properties:
                  error:
                    type: "string"
              links:
                type: "object"
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Organisation"
              links:
                type: "object"
      security:
        - basicAuth: []

  /organisation/{organsiationId}:
    get:
      summary: "Return an organisation"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "organisationId"
          in: "path"
          description: "ID of organisation to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        401:
          description: "Unauthorized"
          schema:
            type: "object"
            properties:
              data:
                type: "object"
                properties:
                  error:
                    type: "string"
              links:
                type: "object"
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Organisation"
              links:
                type: "object"
      security:
        - basicAuth: []

  /groups:
    get:
      summary: "Return all the member groups"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Group"
              links:
                type: "object"
      security:
        - basicAuth: []

  /group/{groupId}:
    get:
      summary: "Return a group"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of group to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        401:
          description: "Unauthorized"
          schema:
            type: "object"
            properties:
              data:
                type: "object"
                properties:
                  error:
                    type: "string"
              links:
                type: "object"
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Group"
              links:
                type: "object"
      security:
        - basicAuth: []

  /scheme:
    post:
      summary: "Create a scheme"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Name of Scheme"
          required: true
          schema:
            $ref: "#/definitions/Scheme"
      responses:
        201:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "object"
                properties:
                  token:
                    type: "string"
              links:
                type: "object"
      security:
        - basicAuth: []


securityDefinitions:
  basicAuth:
    type: basic

definitions:

  Health:
    type: "object"
    properties:
      status:
        type: "string"
        enum:
          - "UP"
          - "DOWN"

  LoginRequest:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"

  Organisation:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      scheme:
        type: "string"
      name:
        type: "string"

  Group:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      organisation:
        type: "string"
      name:
        type: "string"

  Scheme:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
