swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Eco Rewards Hub API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "linusnorton@gmail.com"
schemes:
  - "http"
  - "https"
paths:
  /health:
    get:
      summary: "Check the status of the service"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Health"
  /organisations:
    get:
      summary: "Return all the organisations"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Organisation"
              links:
                type: "object"
      security:
        - basicAuth: []

securityDefinitions:
  basicAuth:
    type: basic
definitions:
  Health:
    type: "object"
    properties:
      status:
        type: "string"
        enum:
          - "UP"
          - "DOWN"
  Organisation:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      scheme:
        type: "string"
      name:
        type: "string"
  Scheme:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
